---
title: "Life_expectancy_analysis"
author: "VMC"
date: "4/27/2021"
output: html_document
---

```{r}
life_expectancy_data <- read.csv("Life Expectancy Data.csv", header = TRUE)
```

# Scatter Plots
```{r}
life_expectancy_data$Developed <- as.integer (as.logical(life_expectancy_data$Status == "Developed"))
plot (life_expectancy_data$Developed, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Developed")
plot (life_expectancy_data$Alcohol, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Alcohol")
plot (life_expectancy_data$percentage.expenditure, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "percentage.expenditure")
plot (life_expectancy_data$Hepatitis.B, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Hepatitis.B")
plot (life_expectancy_data$Measles, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Measles")
plot (life_expectancy_data$BMI, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "BMI")
plot (life_expectancy_data$under.five.deaths, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "under.five.deaths")
plot (life_expectancy_data$Polio, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Polio")
plot (life_expectancy_data$Total.expenditure, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Total.expenditure")
plot (life_expectancy_data$Diphtheria, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Diphtheria")
plot (life_expectancy_data$HIV.AIDS, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "HIV.AIDS")
plot (life_expectancy_data$GDP, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "GDP")
plot (life_expectancy_data$Population, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Population")
plot (life_expectancy_data$thinness..1.19.years, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "thinness..1.19.years")
plot (life_expectancy_data$thinness.5.9.years, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "thinness.5.9.years")
plot (life_expectancy_data$Income.composition.of.resources, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Income.composition.of.resources")
plot (life_expectancy_data$Schooling, life_expectancy_data$Life.expectancy, ylab = "Life Expectancy", xlab = "Schooling")
```

# Histograms
```{r}

hist (life_expectancy_data$Life.expectancy, xlab="Life Expectancy", ylab="Frequency of Life Expectancy", border="green",col="blue")

```












